trigger:
- main

pool:
  name: Shravan   # <-- your agent pool name

steps:
- script: node -v
  displayName: check node

- script: npm install
  displayName: install dependencies

- script: npm run build
  displayName: build react app
